### PR TITLE
Initial PR

### PR DESCRIPTION
**Pull request by ryzokuken**

### CODE REVIEW

**Comment by ryzokuken** [comment]
Update: Added code. @jywarren take a look and tell me if it's good to go.

**Review by jywarren — APPROVED** [review]
Looks super!!!

**Comment by priyansh1161** [comment]
Looks good, but isn't it the code from plotsbot? and how well will it work with a middlewares based arch. ?

**Comment by ryzokuken** [comment]
@priyansh1161 Yes, this is *almost* the exact same code. We could make this work for now (as we already have) until we have a solid working version of the code that implements middlewares better, I think.

What do you say?

**Comment by priyansh1161** [comment]
sounds good to me, we can work on an experimental branch till that happens and then we'll have some breaking changes.

**Comment by ryzokuken** [comment]
Yeah, sure. We'll set up another branch that will hold the code for the big middlewares release and when we're sure it's stable and that we've tied out all the loose ends, we could merge it to master and make a release, making it available to people downstream.

**Comment by ryzokuken** [comment]
Merging this for now. That said, there's still work to be done.

**Pull request merged**
